6 module 2 task
js-tasks-ru/jsbasic-20210621_proskurkinv pull request #6
Opened 2021-07-20 21:20 UTC by FilinCold

2021-07-20 21:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-21 14:46 UTC, SinimaWath requested changes

2021-07-21 14:46 UTC, SinimaWath commented on 6-module/2-task/index.js
> +  _elementsHTML(html) {
Давай лучше используем хелпер, на первой строчки который импортируется

2021-07-21 14:46 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    this._button
getter - нужен для получения значений. Тут ты не используешь результат вызова, поэтому это не геттер

2021-07-21 14:46 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    const buttonEvent = this.elem.querySelector('button[class="card__button"]')
это не buttonEvent, а buttonElement

2021-07-21 14:46 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    const buttonEvent = this.elem.querySelector('button[class="card__button"]')
this.elem.querySelector('.card__button')

не нужно делать селектор button[class="card__button"]

2021-07-21 14:46 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    })
Не надо в задаче выводить это событие

2021-07-21 14:46 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    const event = new CustomEvent("product-add", {bubbles : false, cancelable : true, detail: { id: this._product.id }})
bubbles: true - это событие должно всплывать, чтобы его перехватить

2021-07-21 14:46 UTC, SinimaWath commented on assets/lib/create-element.js
> +  return div;
оставь тут div. firstElementChild.

Для этого этот хелпер и задуман

2021-07-22 12:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-07-22 16:13 UTC, SinimaWath requested changes

2021-07-22 16:13 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this.elem;
А зачем тут получение свойства, без его использования?

2021-07-22 16:13 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    return this.elem = table;
Зачем тут return?

2021-07-22 16:13 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    return this.elem = `
Зачем тут return?

2021-07-22 16:13 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    this.elem;
А зачем тут получение свойства, без его использования?

2021-07-22 16:13 UTC, SinimaWath commented on 6-module/2-task/index.js
> +      });
А зачем тут пустой обработчик события?

2021-07-22 16:13 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    this.elem;
А зачем тут получение свойства, без его использования?

2021-07-22 16:13 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    return this.elem = div;
зачем тут return?

2021-07-22 16:13 UTC, SinimaWath commented on 6-module/3-task/index.js
> +        });
Зачем тут пустой обработчик события?

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    this.elem;
А зачем тут получение свойства, без его использования?

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    return this.title = title;
зачем тут return?

setTitle - должен изменять дом елемент, а не свойство в классе. Вызов этого метода должен влиять на DOM елемент.

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    return this.subtitle = tempStr.replace('%string%', subtitle.outerHTML);
Вызов этого метода должен влиять на DOM елемент.

Также тут тебе не надо получить subtitle из елемента. Просто вставляй его в DOM елемент модального окна

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    this.subtitle;
Не нужно обращаться к свойствам если их не используешь

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    modal.remove();
Зачем из DOM выбираешь елемент? У тебя есть ссылка на него: `this.elem`

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +      divModal.remove();
у тебя точно такойже кода в методе close, вызывай его

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +      }
у тебя точно такойже кода в методе close, вызывай его.

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    this.elem = divModal.innerHTML = `
Зачем тебе тут запись: `this.elem = divModal.innerHTML = ` ? 
В this.elem должен быть готовый DOM елемент

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    modalClose.addEventListener('click', function(e) {
это событие должно срабатывать только один раз, после закрытия, больше не нужно обрабатывать событие

2021-07-22 16:13 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    document.addEventListener('keydown', function(e) {
Это событие должно обрабатываться только один раз. 

В твоем случае, у тебя утечка обработчика события. На каждый вызов метода open создается document.addEventListener('keydown'), но не удаляется

2021-08-07 09:17 UTC, SinimaWath requested changes

2021-08-07 09:17 UTC, SinimaWath commented on 6-module/1-task/index.js
> +      elem.addEventListener('click', (e) => {
Когда удаляешь, подписка на событие тебе уже тоже не нужно. Поэтому тут логично поставить once

2021-08-07 09:17 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    function checkButtonsForShowHidden(wrapperCarousel, getAttrButton, nextSlide, prevSlide) {
Все таки стоит эту функцию вынести в отдельный метод.

2021-08-07 09:17 UTC, SinimaWath commented on 6-module/3-task/index.js
> +    Array.from(listCards).map(card => {
Зачем тут map? Он нужен для изменения елемнтов массива, тут тебе нужно просто итерация, поэтому forEach

2021-08-07 09:17 UTC, SinimaWath commented on 7-module/4-task/index.js
> +  moveSlider() {
Очень сложный метод, давай попробуем его разбить на логические блоки

2025-01-06 06:00 UTC, closed without merging